web:
  build: .
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - .:/code
db:
  image: mysql
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: phpapp
